[package]
edition = "2018"
name = "learn-wgpu"
version = "0.1.0"

[dependencies]
bytemuck = {version = "1.4", features = ["derive"]}
cgmath = "0.18"
env_logger = "0.8"
futures = "0.3"
image = "0.23"
log = "0.4"
wgpu = "0.8"
winit = "0.24"
